### ISSUE TITLE
Misspelled commit message

### ISSUE THREAD

**Issue by res234** [mafetoro92/youtube_practice#1]
Please write "Project" @mafetoro92 

<img width="293" alt="image" src="https://user-images.githubusercontent.com/11264306/108639647-4269ad80-745b-11eb-80fa-461355dea3da.png">

**Comment by mafetoro92** [comment]
@res234 where I need to type project ?

**Comment by res234** [comment]
@mafetoro92 your commit message was misspelled. It's ok. Closing this.
