### ISSUE TITLE
Multiple branches

### ISSUE THREAD

**Issue by res234** [mafetoro92/youtube_practice#3]
We need to have one branch. You have two branches now. Please delete the unnecessary branch @mafetoro92

**Comment by mafetoro92** [comment]
@res234 I made main branch because when I created readme came with that branch

**Comment by res234** [comment]
@mafetoro92 that's ok. It still shouldn't be there. It's unnecessary. Take a look at this link for some help on how to delete it: https://stackoverflow.com/questions/2003505/how-do-i-delete-a-git-branch-locally-and-remotely

**Comment by mafetoro92** [comment]
@res234 I delete the branch and create in master the file README.md

**Comment by res234** [comment]
@mafetoro92 looks so much better!
