### ISSUE TITLE
Need to add a .gitignore

### ISSUE THREAD

**Issue by res234** [mafetoro92/youtube_practice#4]
The repo is huge. Please ignore the files that don't need to be in there. You can read about .gitignore here: https://docs.github.com/en/github/using-git/ignoring-files and find an example of a Python .gitignore here: https://github.com/github/gitignore/blob/master/Python.gitignore

@mafetoro92

**Comment by mafetoro92** [comment]
@res234 Yes, I created already .gitignore, thanks :)

**Comment by res234** [comment]
@mafetoro92 please add these files:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/11264306/108645277-eeb98d00-7477-11eb-86e8-3c4016a48511.png">

Also, get rid of the .mp3 files that are already tracked. See this for help: https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

**Comment by mafetoro92** [comment]
@res234 I dont know what do you mean with add these file is in the repository already. I delete the mp3 file

**Comment by res234** [comment]
@mafetoro92 thanks.

Can you get rid of `.idea`, `__pycache__`, `env` and `.DS_Store`? Add those to the .gitignore as well.

**Comment by mafetoro92** [comment]
@res234 Good morning I add already this folder to .gitignore and the file and folders is no anymore in my repository

**Comment by res234** [comment]
@mafetoro92 looks amazing! From now on please make sure none of those unnecessary files are there. Always have a .gitignore for any project.

You can close this once you've read my message.
