### ISSUE TITLE
Code doesn't follow pep8

### ISSUE THREAD

**Issue by res234** [mafetoro92/youtube_practice#6]
@mafetoro92 Styling of code is important. Please follow pep8: https://www.python.org/dev/peps/pep-0008/

PyCharm has a shortcut to auto format your code: https://www.jetbrains.com/help/pycharm/reformat-file-dialog.html. Please run this before you commit.

**Comment by mafetoro92** [comment]
@res234 Sorry I cant understand, Do you want me to use pep8 in my code for styling the code and I dont understand the second link you send me

**Comment by res234** [comment]
@mafetoro92 Yes you should. PyCharm can format your code for you correctly. The second link shows you how.

**Comment by mafetoro92** [comment]
@res234  I applied in the code pep8 in my proyect
