### ISSUE TITLE
Unnecessary f-strings

### ISSUE THREAD

**Issue by res234** [mafetoro92/youtube_practice#7]
https://github.com/mafetoro92/youtube_practice/blob/96467d0d9ec0a55d9ba3f1adc7ff9f22d2f90b6a/main.py#L30

https://github.com/mafetoro92/youtube_practice/blob/96467d0d9ec0a55d9ba3f1adc7ff9f22d2f90b6a/main.py#L38

There are other places as well where you use an f-string that you shouldn't.

**Comment by mafetoro92** [comment]
@res234 can you tell me what other places I use that for delete?

**Comment by res234** [comment]
@mafetoro92 try to find out on your own :) Just look and see where you're using `f` but it's not necessary.

**Comment by mafetoro92** [comment]
@res234 I delete already all the Unnecessary f-strings thanks
